export const APP_REQUEST_LOGIN = 'APP_REQUEST_LOGIN';
export const APP_SET_AUTH = 'APP_SET_AUTH';

export const APP_REQUEST_USER_DATA = 'APP_REQUEST_USER_DATA';
export const APP_SET_USER_DATA = 'APP_SET_USER_DATA';
